<?php

namespace SfadlessCMF\ContentBundle\Controller;

use SfadlessCMF\ContentBundle\Block\ContentProvider\ContentProviderManager;
use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\HttpFoundation\Request;

/**
 * BlockAdminController
 *
 * @author Pavel Golikov <pgolikov327@gmail.com>
 */
class BlockAdminController extends CRUDController
{
    /**
     * @var ContentProviderManager
     */
    private $contentProviderManager;

    public function contentAction($id)
    {
        dump($this->admin->getSubject());

        die();
    }

    public function createAction(Request $request = null)
    {
        if (!$request->get('provider') && $request->isMethod('get')) {

            return $this->renderWithExtraParams('admin/CRUD/select_block_provider.twig', [
//                'providers' => $pool->getProvidersByContext(
//                    $request->get('context', $pool->getDefaultContext())
//                ),
                'providers' => $this->contentProviderManager->getAll(),
                'action' => 'create',
            ]);
        }

        return parent::createAction(); // TODO: Change the autogenerated stub
    }

    public function __construct(ContentProviderManager $contentProviderManager)
    {
        $this->contentProviderManager = $contentProviderManager;
    }
}
